//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_floral_delivery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registeration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public registeration()
        {
            this.carts = new HashSet<cart>();
            this.billinggs = new HashSet<billingg>();
        }
    
        public int cus_id { get; set; }
        public string F_name { get; set; }
        public string L_name { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> P_No { get; set; }
        public string Address { get; set; }
        public string password { get; set; }
        public string role { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart> carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<billingg> billinggs { get; set; }
    }
}
